UPDATE npcs SET gold = '2' WHERE name = '26-köpfiger Salamander';
UPDATE npcs SET gold = '23' WHERE name = 'Aasgeier';
UPDATE npcs SET gold = '23' WHERE name = 'Abgesandter der Eiswelt (Oberfläche)';
UPDATE npcs SET gold = '6' WHERE name = 'Abgesandter der Eiswelt (Vorhof der Eiswelt)';
UPDATE npcs SET gold = '45' WHERE name = 'Abgestürzte Lichtpflanze';
UPDATE npcs SET gold = '21' WHERE name = 'Abgestürzter Weltraum-Kraken';
UPDATE npcs SET gold = '16' WHERE name = 'Absorbierende Dunkelsee-Qualle';
UPDATE npcs SET gold = '10' WHERE name = 'Abtrünnige Wolke';
UPDATE npcs SET gold = '12' WHERE name = 'Algenechse';
UPDATE npcs SET gold = '28' WHERE name = 'Alte Grottenschlange';
UPDATE npcs SET gold = '6' WHERE name = 'Alte Pilzwachtel';
UPDATE npcs SET gold = '20' WHERE name = 'Alter Frostwolf';
UPDATE npcs SET gold = '12' WHERE name = 'Alter Goldballenwurm';
UPDATE npcs SET gold = '6' WHERE name = 'Alter Mann';
UPDATE npcs SET gold = '0' WHERE name = 'Alter Stororaptor';
UPDATE npcs SET gold = '25' WHERE name = 'Alter Ölfisch';
UPDATE npcs SET gold = '33' WHERE name = 'Altes Blätterwesen';
UPDATE npcs SET gold = '23' WHERE name = 'Altes Kaklatron';
UPDATE npcs SET gold = '2' WHERE name = 'Altstadtratte';
UPDATE npcs SET gold = '32' WHERE name = 'Ameisenhügel';
UPDATE npcs SET gold = '20' WHERE name = 'Anatubischer Windhund';
UPDATE npcs SET gold = '8' WHERE name = 'Angebissene Lianenechse';
UPDATE npcs SET gold = '28' WHERE name = 'Aschenvogel';
UPDATE npcs SET gold = '1' WHERE name = 'Astgreifer';
UPDATE npcs SET gold = '60' WHERE name = 'Aufgeregter Nebelhüpfer';
UPDATE npcs SET gold = '5' WHERE name = 'Ausgesaugter Energiewurm';
UPDATE npcs SET gold = '14' WHERE name = 'Ausgestoßener Glypra';
UPDATE npcs SET gold = '12' WHERE name = 'Ausgewachsener Strativar';
UPDATE npcs SET gold = '50' WHERE name = 'Baby-Einflügler';
UPDATE npcs SET gold = '16' WHERE name = 'Badender Frostwolf-Welpe';
UPDATE npcs SET gold = '15' WHERE name = 'Baru-Giftegel';
UPDATE npcs SET gold = '20' WHERE name = 'Baru-Schrecke';
UPDATE npcs SET gold = '16' WHERE name = 'Baumkuschler';
UPDATE npcs SET gold = '2' WHERE name = 'Behüter der Kathedrale';
UPDATE npcs SET gold = '17' WHERE name = 'Belebender Falter';
UPDATE npcs SET gold = '2' WHERE name = 'Belpharia-Tucan';
UPDATE npcs SET gold = '23' WHERE name = 'Bemooster Felsblock';
UPDATE npcs SET gold = '40' WHERE name = 'Benebeltes Mormdat';
UPDATE npcs SET gold = '29' WHERE name = 'Berghund';
UPDATE npcs SET gold = '8' WHERE name = 'Bergpilz';
UPDATE npcs SET gold = '80' WHERE name = 'Bernstein-Dokun';
UPDATE npcs SET gold = '36' WHERE name = 'Bernstein-Falke';
UPDATE npcs SET gold = '28' WHERE name = 'Bernstein-Raupe';
UPDATE npcs SET gold = '14' WHERE name = 'Bestialisches Tonar-Reptil';
UPDATE npcs SET gold = '0' WHERE name = 'Betrunkener Rabauke';
UPDATE npcs SET gold = '20' WHERE name = 'Beuteltiger';
UPDATE npcs SET gold = '13' WHERE name = 'Bissiger Ölfisch';
UPDATE npcs SET gold = '33' WHERE name = 'Blattalisk';
UPDATE npcs SET gold = '23' WHERE name = 'Blattspinne';
UPDATE npcs SET gold = '100' WHERE name = 'Blauer Landfisch';
UPDATE npcs SET gold = '12' WHERE name = 'Blauer Stachelschuss-Igel';
UPDATE npcs SET gold = '20' WHERE name = 'Blauer Todesläufer';
UPDATE npcs SET gold = '120' WHERE name = 'Blaues Glühwürmchen';
UPDATE npcs SET gold = '2' WHERE name = 'Blaues Stachel-Kowu';
UPDATE npcs SET gold = '1' WHERE name = 'Blaukamm-Vogel';
UPDATE npcs SET gold = '12' WHERE name = 'Blauschimmer-Ameise';
UPDATE npcs SET gold = '21' WHERE name = 'Blauwaldwurm';
UPDATE npcs SET gold = '15' WHERE name = 'Blumenbeißer';
UPDATE npcs SET gold = '0' WHERE name = 'Blumenkasten';
UPDATE npcs SET gold = '1' WHERE name = 'Blutameise';
UPDATE npcs SET gold = '34' WHERE name = 'Blutapfelbaum';
UPDATE npcs SET gold = '1' WHERE name = 'Blutblatt';
UPDATE npcs SET gold = '1' WHERE name = 'Blutblob';
UPDATE npcs SET gold = '8' WHERE name = 'Blutende Lianenschlinge';
UPDATE npcs SET gold = '2' WHERE name = 'Blutforsch';
UPDATE npcs SET gold = '1' WHERE name = 'Blutgeflecht';
UPDATE npcs SET gold = '1' WHERE name = 'Blutharzgeschoss';
UPDATE npcs SET gold = '1' WHERE name = 'Blutharzregen';
UPDATE npcs SET gold = '1' WHERE name = 'Blutharztropfen';
UPDATE npcs SET gold = '32' WHERE name = 'Blutige Peitschenliane';
UPDATE npcs SET gold = '4' WHERE name = 'Blutiges Schaf';
UPDATE npcs SET gold = '1' WHERE name = 'Blutkrähe';
UPDATE npcs SET gold = '1' WHERE name = 'Blutkäfer';
UPDATE npcs SET gold = '0' WHERE name = 'Blutprobenwesen';
UPDATE npcs SET gold = '1' WHERE name = 'Blutrabe';
UPDATE npcs SET gold = '1' WHERE name = 'Blutspinne';
UPDATE npcs SET gold = '1' WHERE name = 'Blutspinnennetz';
UPDATE npcs SET gold = '1' WHERE name = 'Blutwanze';
UPDATE npcs SET gold = '23' WHERE name = 'Blutwurm';
UPDATE npcs SET gold = '5' WHERE name = 'Bockiger Stier';
UPDATE npcs SET gold = '1' WHERE name = 'Borkende Blutbirke';
UPDATE npcs SET gold = '17' WHERE name = 'Borstenfisch';
UPDATE npcs SET gold = '12' WHERE name = 'Brennendes Schaf';
UPDATE npcs SET gold = '5' WHERE name = 'Bruder des Nebelbesens';
UPDATE npcs SET gold = '8' WHERE name = 'Brummkäfer';
UPDATE npcs SET gold = '10' WHERE name = 'Brutaler Fallensteller';
UPDATE npcs SET gold = '0' WHERE name = 'Brznkk Gttsnz';
UPDATE npcs SET gold = '25' WHERE name = 'Bulliges Erd-Skelkos';
UPDATE npcs SET gold = '55' WHERE name = 'Busch-Frul';
UPDATE npcs SET gold = '5' WHERE name = 'Bücherwurm';
UPDATE npcs SET gold = '17' WHERE name = 'Chiup-Vogel';
UPDATE npcs SET gold = '2' WHERE name = 'Crim Garaank';
UPDATE npcs SET gold = '40' WHERE name = 'Deckenkleiber';
UPDATE npcs SET gold = '12' WHERE name = 'Denkender Lavablob';
UPDATE npcs SET gold = '20' WHERE name = 'Dicke, fette Strandkrabbe';
UPDATE npcs SET gold = '9' WHERE name = 'Dicker Zukuvogel';
UPDATE npcs SET gold = '16' WHERE name = 'Dickhäutiger Goldballenwurm';
UPDATE npcs SET gold = '12' WHERE name = 'Dickhäutiger Graustein-Bär';
UPDATE npcs SET gold = '0' WHERE name = 'Diebstahlfalle (NPC)';
UPDATE npcs SET gold = '10' WHERE name = 'Diebstahlfallen-Verwalter';
UPDATE npcs SET gold = '50' WHERE name = 'Diener des Feuers';
UPDATE npcs SET gold = '3' WHERE name = 'Diener von Beispieluser';
UPDATE npcs SET gold = '2' WHERE name = 'Dilinug';
UPDATE npcs SET gold = '18' WHERE name = 'Donnersandschlange';
UPDATE npcs SET gold = '63' WHERE name = 'Donnerstier';
UPDATE npcs SET gold = '14' WHERE name = 'Doppelköpfiger Riesenskorpion';
UPDATE npcs SET gold = '7' WHERE name = 'Dradonfalter';
UPDATE npcs SET gold = '2' WHERE name = 'Dreiköpfige Wasserschlange';
UPDATE npcs SET gold = '7' WHERE name = 'Dreiäugiger Stier';
UPDATE npcs SET gold = '13' WHERE name = 'Duftendes Grünschleimwesen';
UPDATE npcs SET gold = '12' WHERE name = 'Dummer Lavablob';
UPDATE npcs SET gold = '3' WHERE name = 'Dunbrakatze';
UPDATE npcs SET gold = '8' WHERE name = 'Dunkelgrottenpilz';
UPDATE npcs SET gold = '80' WHERE name = 'Dunkelmorin';
UPDATE npcs SET gold = '26' WHERE name = 'Dunkelmorin-Skelett';
UPDATE npcs SET gold = '7' WHERE name = 'Dunkelsand-Schmetterling';
UPDATE npcs SET gold = '25' WHERE name = 'Dunkelsandkrebs';
UPDATE npcs SET gold = '100' WHERE name = 'Dunkelschlamm-Wurm';
UPDATE npcs SET gold = '14' WHERE name = 'Dunkelsee-Qualle';
UPDATE npcs SET gold = '21' WHERE name = 'Dunkelstern-Arbeiter';
UPDATE npcs SET gold = '29' WHERE name = 'Dunkelstern-Krieger';
UPDATE npcs SET gold = '33' WHERE name = 'Dunkelstern-Magier';
UPDATE npcs SET gold = '2' WHERE name = 'Dunkelstern-Seher';
UPDATE npcs SET gold = '100' WHERE name = 'Dunkelwald-Skelett';
UPDATE npcs SET gold = '7' WHERE name = 'Dunkelwanze';
UPDATE npcs SET gold = '23' WHERE name = 'Dunkle Sandratte';
UPDATE npcs SET gold = '2' WHERE name = 'Dunkler Matschreißer';
UPDATE npcs SET gold = '80' WHERE name = 'Dunkler Sandtaprap';
UPDATE npcs SET gold = '46' WHERE name = 'Dunkler Schamane';
UPDATE npcs SET gold = '30' WHERE name = 'Durchgedrehter Felsenschreier';
UPDATE npcs SET gold = '10' WHERE name = 'Durstige Riesenlibelle';
UPDATE npcs SET gold = '2' WHERE name = 'Dämonenhund';
UPDATE npcs SET gold = '14' WHERE name = 'Dämonisches Grünschleimwesen';
UPDATE npcs SET gold = '1' WHERE name = 'Ein Schwarm Blutkrähen';
UPDATE npcs SET gold = '1' WHERE name = 'Eine Schar Blutraben';
UPDATE npcs SET gold = '50' WHERE name = 'Einflügler';
UPDATE npcs SET gold = '12' WHERE name = 'Einsamer Schneehase';
UPDATE npcs SET gold = '12' WHERE name = 'Einsamer Waldhüpfer';
UPDATE npcs SET gold = '28' WHERE name = 'Einäugiger Stier';
UPDATE npcs SET gold = '21' WHERE name = 'Eisbohrmaschine';
UPDATE npcs SET gold = '21' WHERE name = 'Eisbohrmaschine-Prototyp';
UPDATE npcs SET gold = '34' WHERE name = 'Eisvogel';
UPDATE npcs SET gold = '50' WHERE name = 'Eiswelt-Echse';
UPDATE npcs SET gold = '17' WHERE name = 'Eiswurm';
UPDATE npcs SET gold = '36' WHERE name = 'Ektofron';
UPDATE npcs SET gold = '15' WHERE name = 'Energetischer Falter';
UPDATE npcs SET gold = '17' WHERE name = 'Energiewurm';
UPDATE npcs SET gold = '15' WHERE name = 'Enorme Stachelschildkröte';
UPDATE npcs SET gold = '12' WHERE name = 'Enormer Graustein-Bär';
UPDATE npcs SET gold = '5' WHERE name = 'Entflohener Mörder';
UPDATE npcs SET gold = '4' WHERE name = 'Entlaufene Geisterschabe';
UPDATE npcs SET gold = '25' WHERE name = 'Erd-Skelkos';
UPDATE npcs SET gold = '20' WHERE name = 'Erdfisch';
UPDATE npcs SET gold = '2' WHERE name = 'Erdkäfer';
UPDATE npcs SET gold = '32' WHERE name = 'Erdschlurch';
UPDATE npcs SET gold = '23' WHERE name = 'Erdvogel';
UPDATE npcs SET gold = '16' WHERE name = 'Erfahrener Frostwolf';
UPDATE npcs SET gold = '0' WHERE name = 'Erfrorenes Schaf';
UPDATE npcs SET gold = '6' WHERE name = 'Erschöpfte Klauenratte';
UPDATE npcs SET gold = '17' WHERE name = 'Ertrinkender Energiewurm';
UPDATE npcs SET gold = '12' WHERE name = 'Exil-Nomade';
UPDATE npcs SET gold = '5' WHERE name = 'Exotischer Fisch';
UPDATE npcs SET gold = '1' WHERE name = 'Experimental-Phasenwesen';
UPDATE npcs SET gold = '0' WHERE name = 'Explosionsfalle (NPC)';
UPDATE npcs SET gold = '0' WHERE name = 'Fahrender Händler';
UPDATE npcs SET gold = '8' WHERE name = 'Fallensteller';
UPDATE npcs SET gold = '2' WHERE name = 'Feldhase';
UPDATE npcs SET gold = '33' WHERE name = 'Felsenechse';
UPDATE npcs SET gold = '25' WHERE name = 'Felsenkriecher';
UPDATE npcs SET gold = '30' WHERE name = 'Felsenschreier';
UPDATE npcs SET gold = '29' WHERE name = 'Felsenwurm';
UPDATE npcs SET gold = '69' WHERE name = 'Feuergeist';
UPDATE npcs SET gold = '16' WHERE name = 'Feuerlaub-Echse';
UPDATE npcs SET gold = '45' WHERE name = 'Feuerlurch';
UPDATE npcs SET gold = '69' WHERE name = 'Feuervogel';
UPDATE npcs SET gold = '100' WHERE name = 'Feuerwachtel';
UPDATE npcs SET gold = '23' WHERE name = 'Feuerwolf';
UPDATE npcs SET gold = '0' WHERE name = 'Feueröl-Händler';
UPDATE npcs SET gold = '0' WHERE name = 'Finstereis-Bewacher';
UPDATE npcs SET gold = '12' WHERE name = 'Flammendes Glühwürmchen';
UPDATE npcs SET gold = '10' WHERE name = 'Flammenwurm';
UPDATE npcs SET gold = '26' WHERE name = 'Flecken-Wolf';
UPDATE npcs SET gold = '8' WHERE name = 'Fleckfarbenfisch';
UPDATE npcs SET gold = '23' WHERE name = 'Fleischfressende Sao-Pflanze';
UPDATE npcs SET gold = '23' WHERE name = 'Fleißiges Lichtwesen';
UPDATE npcs SET gold = '6' WHERE name = 'Fliegende Kuh';
UPDATE npcs SET gold = '20' WHERE name = 'Fliegende Nebelkugel';
UPDATE npcs SET gold = '150' WHERE name = 'Fliegender Todesfarn';
UPDATE npcs SET gold = '15' WHERE name = 'Flimmernde Farbanomalie';
UPDATE npcs SET gold = '37' WHERE name = 'Flinker Bernstein-Falke';
UPDATE npcs SET gold = '0' WHERE name = 'Fluktuatives Zauberlabor';
UPDATE npcs SET gold = '1' WHERE name = 'Flüstergeist';
UPDATE npcs SET gold = '8' WHERE name = 'Frierender Schneefisch';
UPDATE npcs SET gold = '12' WHERE name = 'Frierender Schneekäfer';
UPDATE npcs SET gold = '12' WHERE name = 'Frierender Schneewurm';
UPDATE npcs SET gold = '2' WHERE name = 'Frierendes Schneewiesel';
UPDATE npcs SET gold = '70' WHERE name = 'Frost-Wiesel';
UPDATE npcs SET gold = '30' WHERE name = 'Frostaugen-Bestie';
UPDATE npcs SET gold = '20' WHERE name = 'Frostdämon';
UPDATE npcs SET gold = '34' WHERE name = 'Frostgeist';
UPDATE npcs SET gold = '16' WHERE name = 'Frostwolf';
UPDATE npcs SET gold = '16' WHERE name = 'Frostwolf-Anführer';
UPDATE npcs SET gold = '16' WHERE name = 'Frostwolf-Welpe';
UPDATE npcs SET gold = '12' WHERE name = 'Gardu-Strauchkäfer';
UPDATE npcs SET gold = '30' WHERE name = 'Gefallener Spindelschreiter';
UPDATE npcs SET gold = '12' WHERE name = 'Gefleckte Riesenlibelle';
UPDATE npcs SET gold = '18' WHERE name = 'Gefrässiger Schattensalamander';
UPDATE npcs SET gold = '18' WHERE name = 'Gefräßige Schotterraupe';
UPDATE npcs SET gold = '2' WHERE name = 'Gefährliches Tier';
UPDATE npcs SET gold = '23' WHERE name = 'Geist der Depressionen';
UPDATE npcs SET gold = '34' WHERE name = 'Geist der Finsternis';
UPDATE npcs SET gold = '29' WHERE name = 'Geist der Welt';
UPDATE npcs SET gold = '80' WHERE name = 'Geist von Pur Pur';
UPDATE npcs SET gold = '28' WHERE name = 'Geister-Undaron';
UPDATE npcs SET gold = '4' WHERE name = 'Geisterschabe';
UPDATE npcs SET gold = '28' WHERE name = 'Geknickter lebender Ast';
UPDATE npcs SET gold = '7' WHERE name = 'Gelangweilter Fallensteller';
UPDATE npcs SET gold = '92' WHERE name = 'Gelbbart-Yeti';
UPDATE npcs SET gold = '12' WHERE name = 'Gelbkatze';
UPDATE npcs SET gold = '8' WHERE name = 'Gemeiner Unterwelt-Dämon';
UPDATE npcs SET gold = '15' WHERE name = 'Gepanzertes Undaron';
UPDATE npcs SET gold = '28' WHERE name = 'Gepforn';
UPDATE npcs SET gold = '16' WHERE name = 'Geröllschlange';
UPDATE npcs SET gold = '24' WHERE name = 'Geröllwiesenschlange';
UPDATE npcs SET gold = '8' WHERE name = 'Geschwächter Abgesandter';
UPDATE npcs SET gold = '5' WHERE name = 'Geschwächtes Kaklatron';
UPDATE npcs SET gold = '40' WHERE name = 'Geysir-Schlucker';
UPDATE npcs SET gold = '28' WHERE name = 'Giftbeißer';
UPDATE npcs SET gold = '0' WHERE name = 'Giftfalle (NPC)';
UPDATE npcs SET gold = '2' WHERE name = 'Giftgeist von Narubia';
UPDATE npcs SET gold = '92' WHERE name = 'Giftgrabl';
UPDATE npcs SET gold = '28' WHERE name = 'Giftschleimer';
UPDATE npcs SET gold = '21' WHERE name = 'Giftsporenpilz';
UPDATE npcs SET gold = '1' WHERE name = 'Gigantischer Spindelschreiter';
UPDATE npcs SET gold = '21' WHERE name = 'Gigantischer Todesläufer';
UPDATE npcs SET gold = '57' WHERE name = 'Gipfellöwe';
UPDATE npcs SET gold = '42' WHERE name = 'Glaswasserfisch';
UPDATE npcs SET gold = '12' WHERE name = 'Gletscherente';
UPDATE npcs SET gold = '17' WHERE name = 'Glibbriger Eiswurm';
UPDATE npcs SET gold = '16' WHERE name = 'Glitschige Dunkelsee-Qualle';
UPDATE npcs SET gold = '46' WHERE name = 'Glutlichtfalter';
UPDATE npcs SET gold = '14' WHERE name = 'Glypra';
UPDATE npcs SET gold = '18' WHERE name = 'Glypra-Spion';
UPDATE npcs SET gold = '14' WHERE name = 'Glypra-Späher';
UPDATE npcs SET gold = '80' WHERE name = 'Glühende Staubechse';
UPDATE npcs SET gold = '12' WHERE name = 'Glühwürmchen';
UPDATE npcs SET gold = '12' WHERE name = 'Goldballenwurm';
UPDATE npcs SET gold = '15' WHERE name = 'Goldener Flutentaucher';
UPDATE npcs SET gold = '28' WHERE name = 'Goldener Undaronwächter';
UPDATE npcs SET gold = '1' WHERE name = 'Goldfadenwurm';
UPDATE npcs SET gold = '23' WHERE name = 'Goldflossenfisch';
UPDATE npcs SET gold = '80' WHERE name = 'Goldhornziege';
UPDATE npcs SET gold = '0' WHERE name = 'Goldkiste';
UPDATE npcs SET gold = '2' WHERE name = 'Goldkraken';
UPDATE npcs SET gold = '23' WHERE name = 'Goldkrebs';
UPDATE npcs SET gold = '2' WHERE name = 'Goldkuh';
UPDATE npcs SET gold = '57' WHERE name = 'Goldwurm';
UPDATE npcs SET gold = '23' WHERE name = 'Goldwächter';
UPDATE npcs SET gold = '23' WHERE name = 'Grabfliege';
UPDATE npcs SET gold = '80' WHERE name = 'Grabgeist der vermissten Toten';
UPDATE npcs SET gold = '25' WHERE name = 'Grabräuber';
UPDATE npcs SET gold = '70' WHERE name = 'Grabschlecker';
UPDATE npcs SET gold = '24' WHERE name = 'Grabwurm';
UPDATE npcs SET gold = '1' WHERE name = 'Grafrather Stechmückenschwarm';
UPDATE npcs SET gold = '16' WHERE name = 'Grasblatt-Schlange';
UPDATE npcs SET gold = '24' WHERE name = 'Graswiesenschlange';
UPDATE npcs SET gold = '12' WHERE name = 'Gratrat-Alien';
UPDATE npcs SET gold = '5' WHERE name = 'Graubartechse';
UPDATE npcs SET gold = '45' WHERE name = 'Graugoldfalter';
UPDATE npcs SET gold = '15' WHERE name = 'Graustein-Bär';
UPDATE npcs SET gold = '23' WHERE name = 'Grottenschlange';
UPDATE npcs SET gold = '2' WHERE name = 'Großer Blattalisk';
UPDATE npcs SET gold = '18' WHERE name = 'Großer Bohnenschnapper';
UPDATE npcs SET gold = '12' WHERE name = 'Großer Erdkäfer';
UPDATE npcs SET gold = '92' WHERE name = 'Großer Laubbär';
UPDATE npcs SET gold = '46' WHERE name = 'Großer Lava-Käfer';
UPDATE npcs SET gold = '40' WHERE name = 'Großer Nebelkreischer';
UPDATE npcs SET gold = '1' WHERE name = 'Großer Phasenvogel';
UPDATE npcs SET gold = '100' WHERE name = 'Großer Prärieskorpion';
UPDATE npcs SET gold = '8' WHERE name = 'Großer Schatten der Dunkelheit';
UPDATE npcs SET gold = '39' WHERE name = 'Großer Wurzelwurm';
UPDATE npcs SET gold = '2' WHERE name = 'Großes Eistentakel';
UPDATE npcs SET gold = '57' WHERE name = 'Grunulum';
UPDATE npcs SET gold = '100' WHERE name = 'Grünbaum-Affe';
UPDATE npcs SET gold = '2' WHERE name = 'Grüne Rotorlibelle';
UPDATE npcs SET gold = '2' WHERE name = 'Grünes Stachel-Kowu';
UPDATE npcs SET gold = '9' WHERE name = 'Grünschimmer-Ameise';
UPDATE npcs SET gold = '16' WHERE name = 'Gurdz-Beerenstrauch';
UPDATE npcs SET gold = '0' WHERE name = 'Handwerker';
UPDATE npcs SET gold = '24' WHERE name = 'Hangstelzer';
UPDATE npcs SET gold = '20' WHERE name = 'Harmloser Giftsporenpilz';
UPDATE npcs SET gold = '2' WHERE name = 'Hase';
UPDATE npcs SET gold = '2' WHERE name = 'Heilender Baum (NPC)';
UPDATE npcs SET gold = '2' WHERE name = 'Herrscher der eisigen Dämonen';
UPDATE npcs SET gold = '57' WHERE name = 'Herz des Blutwaldes';
UPDATE npcs SET gold = '25' WHERE name = 'Hinterlistiger Stororaptor';
UPDATE npcs SET gold = '3' WHERE name = 'Holz-Maus';
UPDATE npcs SET gold = '8' WHERE name = 'Holzplatten-Schildkröte';
UPDATE npcs SET gold = '0' WHERE name = 'Hornrücken';
UPDATE npcs SET gold = '8' WHERE name = 'Hulnodar-Heiler';
UPDATE npcs SET gold = '0' WHERE name = 'Hulnodar-Kiste';
UPDATE npcs SET gold = '26' WHERE name = 'Hulnodar-Wächter';
UPDATE npcs SET gold = '2' WHERE name = 'Hundertfüßiger Dilinug';
UPDATE npcs SET gold = '17' WHERE name = 'Hyperaktiver Waldhüpfer';
UPDATE npcs SET gold = '32' WHERE name = 'Hyäne';
UPDATE npcs SET gold = '57' WHERE name = 'Höhlenbär';
UPDATE npcs SET gold = '23' WHERE name = 'Höhlenmensch';
UPDATE npcs SET gold = '28' WHERE name = 'Insel-Schnapper';
UPDATE npcs SET gold = '10' WHERE name = 'Itolos-Schrecke';
UPDATE npcs SET gold = '90' WHERE name = 'Jerodar-Anführer';
UPDATE npcs SET gold = '1' WHERE name = 'Jerodar-Dieb';
UPDATE npcs SET gold = '1' WHERE name = 'Jerodar-Erdwühler';
UPDATE npcs SET gold = '0' WHERE name = 'Jerodar-Kiste';
UPDATE npcs SET gold = '1' WHERE name = 'Jerodar-Lehrling';
UPDATE npcs SET gold = '5' WHERE name = 'Junger Abgesandter';
UPDATE npcs SET gold = '92' WHERE name = 'Junger Giftgrabl';
UPDATE npcs SET gold = '10' WHERE name = 'Junger Graustein-Bär';
UPDATE npcs SET gold = '5' WHERE name = 'Junger Schatten der Dunkelheit';
UPDATE npcs SET gold = '6' WHERE name = 'Junger Stororaptor';
UPDATE npcs SET gold = '6' WHERE name = 'Junger Strativar';
UPDATE npcs SET gold = '23' WHERE name = 'Kaklatron';
UPDATE npcs SET gold = '32' WHERE name = 'Kanal-Krake';
UPDATE npcs SET gold = '38' WHERE name = 'Kanalqualle';
UPDATE npcs SET gold = '1' WHERE name = 'Kastanienträne';
UPDATE npcs SET gold = '0' WHERE name = 'Kellerkiste';
UPDATE npcs SET gold = '0' WHERE name = 'Kiste der Festung';
UPDATE npcs SET gold = '0' WHERE name = 'Klapperschlange';
UPDATE npcs SET gold = '150' WHERE name = 'Klauenbartrein';
UPDATE npcs SET gold = '22' WHERE name = 'Klauenratte';
UPDATE npcs SET gold = '1' WHERE name = 'Kleine Blutratte';
UPDATE npcs SET gold = '1' WHERE name = 'Kleine Blutweide';
UPDATE npcs SET gold = '10' WHERE name = 'Kleine Farbanomalie';
UPDATE npcs SET gold = '19' WHERE name = 'Kleine Grottenschlange';
UPDATE npcs SET gold = '2' WHERE name = 'Kleine Luftschnecke';
UPDATE npcs SET gold = '23' WHERE name = 'Kleine Spinne';
UPDATE npcs SET gold = '1' WHERE name = 'Kleine Stachelmade';
UPDATE npcs SET gold = '14' WHERE name = 'Kleiner Laubbär';
UPDATE npcs SET gold = '30' WHERE name = 'Kleiner Nebelkreischer';
UPDATE npcs SET gold = '1' WHERE name = 'Kleiner Phasenbär';
UPDATE npcs SET gold = '1' WHERE name = 'Kleiner Spindelschreiter';
UPDATE npcs SET gold = '57' WHERE name = 'Kleiner Steingolem';
UPDATE npcs SET gold = '8' WHERE name = 'Kleiner Waldschlurch';
UPDATE npcs SET gold = '12' WHERE name = 'Kleines Haus-Schaf';
UPDATE npcs SET gold = '6' WHERE name = 'Kleines Reen';
UPDATE npcs SET gold = '12' WHERE name = 'Kleines Schaf';
UPDATE npcs SET gold = '1' WHERE name = 'Kleines Schlangentier';
UPDATE npcs SET gold = '57' WHERE name = 'Knochensammler';
UPDATE npcs SET gold = '1' WHERE name = 'Knorpel-Monster aus Draht (NPC)';
UPDATE npcs SET gold = '1' WHERE name = 'Knorrige Wurzel';
UPDATE npcs SET gold = '8' WHERE name = 'Knunglo';
UPDATE npcs SET gold = '0' WHERE name = 'Knurrender Goldballenwurm';
UPDATE npcs SET gold = '100' WHERE name = 'Kollektiver Salzhügel';
UPDATE npcs SET gold = '2' WHERE name = 'Koloa-Käfer';
UPDATE npcs SET gold = '80' WHERE name = 'Kopolaspinne';
UPDATE npcs SET gold = '10' WHERE name = 'Kraftvoller Sporenträger';
UPDATE npcs SET gold = '23' WHERE name = 'Kranke Grottenschlange';
UPDATE npcs SET gold = '6' WHERE name = 'Kranke Milchkuh';
UPDATE npcs SET gold = '8' WHERE name = 'Kranker Todesläufer';
UPDATE npcs SET gold = '2' WHERE name = 'Kranker Wüstensalamander';
UPDATE npcs SET gold = '9' WHERE name = 'Kriechlapf';
UPDATE npcs SET gold = '2' WHERE name = 'Kristall-Orwane';
UPDATE npcs SET gold = '23' WHERE name = 'Kristallfisch';
UPDATE npcs SET gold = '35' WHERE name = 'Kristallwasserpflanze';
UPDATE npcs SET gold = '9' WHERE name = 'Krumme Grünschimmer-Ameise';
UPDATE npcs SET gold = '28' WHERE name = 'Krustenkäfer';
UPDATE npcs SET gold = '15' WHERE name = 'Kräftiger Graustein-Bär';
UPDATE npcs SET gold = '20' WHERE name = 'Kurnotan - der dunkle Magier';
UPDATE npcs SET gold = '23' WHERE name = 'Lablabkaktus';
UPDATE npcs SET gold = '14' WHERE name = 'Langfaden-Spinne';
UPDATE npcs SET gold = '23' WHERE name = 'Langzahnaffe';
UPDATE npcs SET gold = '0' WHERE name = 'Larafstrauch';
UPDATE npcs SET gold = '2' WHERE name = 'Larpan';
UPDATE npcs SET gold = '12' WHERE name = 'Larvennest';
UPDATE npcs SET gold = '24' WHERE name = 'Laubwiesenschlange';
UPDATE npcs SET gold = '28' WHERE name = 'Lava Echse';
UPDATE npcs SET gold = '31' WHERE name = 'Lava-Käfer';
UPDATE npcs SET gold = '28' WHERE name = 'Lava-Wurm';
UPDATE npcs SET gold = '34' WHERE name = 'Lawinengeist';
UPDATE npcs SET gold = '115' WHERE name = 'Lebende Bergspitze';
UPDATE npcs SET gold = '0' WHERE name = 'Lebende Statue';
UPDATE npcs SET gold = '30' WHERE name = 'Lebende Waldwurzel';
UPDATE npcs SET gold = '90' WHERE name = 'Lebender Ast';
UPDATE npcs SET gold = '12' WHERE name = 'Lebender Salzhügel';
UPDATE npcs SET gold = '2' WHERE name = 'Lebender Tropfstein';
UPDATE npcs SET gold = '0' WHERE name = 'Lehrlingskiste';
UPDATE npcs SET gold = '1' WHERE name = 'Lernfähiger Spindelschreiter';
UPDATE npcs SET gold = '13' WHERE name = 'Leuchtende Dunkelsee-Qualle';
UPDATE npcs SET gold = '22' WHERE name = 'Lianenechse';
UPDATE npcs SET gold = '90' WHERE name = 'Lichtpflanze';
UPDATE npcs SET gold = '3' WHERE name = 'Lichtwurm';
UPDATE npcs SET gold = '0' WHERE name = 'Lola - Die Hauskawutze';
UPDATE npcs SET gold = '100' WHERE name = 'Loroktom, der große Steingolem';
UPDATE npcs SET gold = '2' WHERE name = 'Magier der dunklen Macht';
UPDATE npcs SET gold = '22' WHERE name = 'Magier des Schutzes';
UPDATE npcs SET gold = '15' WHERE name = 'Magische Farbanomalie';
UPDATE npcs SET gold = '46' WHERE name = 'Manticore';
UPDATE npcs SET gold = '2' WHERE name = 'Massive Landqualle';
UPDATE npcs SET gold = '20' WHERE name = 'Metallischer Morschgreifer';
UPDATE npcs SET gold = '6' WHERE name = 'Milchkuh';
UPDATE npcs SET gold = '34' WHERE name = 'Moorgeist';
UPDATE npcs SET gold = '23' WHERE name = 'Moosgeflecht';
UPDATE npcs SET gold = '23' WHERE name = 'Moosspinne';
UPDATE npcs SET gold = '0' WHERE name = 'Mopfchen';
UPDATE npcs SET gold = '40' WHERE name = 'Mormdat';
UPDATE npcs SET gold = '16' WHERE name = 'Morschgreifer';
UPDATE npcs SET gold = '15' WHERE name = 'Morschwaldaffe';
UPDATE npcs SET gold = '40' WHERE name = 'Murmelndes Mormdat';
UPDATE npcs SET gold = '150' WHERE name = 'Mutierter Koloa-Käfer';
UPDATE npcs SET gold = '80' WHERE name = 'Mutierter Morschgreifer';
UPDATE npcs SET gold = '40' WHERE name = 'Mutiges Mormdat';
UPDATE npcs SET gold = '24' WHERE name = 'Mutter der Geysir-Schlucker';
UPDATE npcs SET gold = '25' WHERE name = 'Nachtfledermaus';
UPDATE npcs SET gold = '34' WHERE name = 'Nachtgonk';
UPDATE npcs SET gold = '35' WHERE name = 'Nachtgonk (Quest)';
UPDATE npcs SET gold = '69' WHERE name = 'Nachtgonk im dunklen Haus';
UPDATE npcs SET gold = '6' WHERE name = 'Nachtschattenraupe';
UPDATE npcs SET gold = '15' WHERE name = 'Narbiger Schneewurm';
UPDATE npcs SET gold = '12' WHERE name = 'Naurofbusch';
UPDATE npcs SET gold = '5' WHERE name = 'Nebelbesen';
UPDATE npcs SET gold = '1' WHERE name = 'Nebelblume';
UPDATE npcs SET gold = '59' WHERE name = 'Nebelgeist Argarie';
UPDATE npcs SET gold = '60' WHERE name = 'Nebelgeist Bargu';
UPDATE npcs SET gold = '25' WHERE name = 'Nebelgeist Frorie';
UPDATE npcs SET gold = '60' WHERE name = 'Nebelgeist Girie';
UPDATE npcs SET gold = '75' WHERE name = 'Nebelgeist Murahn';
UPDATE npcs SET gold = '75' WHERE name = 'Nebelgeist Napirie';
UPDATE npcs SET gold = '25' WHERE name = 'Nebelgeist Nukarie';
UPDATE npcs SET gold = '60' WHERE name = 'Nebelgeist Sorlie';
UPDATE npcs SET gold = '60' WHERE name = 'Nebelgeist Viginur';
UPDATE npcs SET gold = '75' WHERE name = 'Nebelgeist Wrozie';
UPDATE npcs SET gold = '11' WHERE name = 'Nebelhüpfer';
UPDATE npcs SET gold = '25' WHERE name = 'Nebelkrebs';
UPDATE npcs SET gold = '40' WHERE name = 'Nebelkreischer';
UPDATE npcs SET gold = '18' WHERE name = 'Nebelkrähe';
UPDATE npcs SET gold = '2' WHERE name = 'Nebelkröte';
UPDATE npcs SET gold = '58' WHERE name = 'Nebelschleimer';
UPDATE npcs SET gold = '5' WHERE name = 'Nebelschnecke';
UPDATE npcs SET gold = '57' WHERE name = 'Nebelwesen';
UPDATE npcs SET gold = '2' WHERE name = 'Nebelwiesel';
UPDATE npcs SET gold = '100' WHERE name = 'Nebelwolf';
UPDATE npcs SET gold = '12' WHERE name = 'Nomade';
UPDATE npcs SET gold = '7' WHERE name = 'Norpi';
UPDATE npcs SET gold = '28' WHERE name = 'Onlo-Skelett';
UPDATE npcs SET gold = '23' WHERE name = 'Panzerrochen';
UPDATE npcs SET gold = '16' WHERE name = 'Parfugurn';
UPDATE npcs SET gold = '25' WHERE name = 'Peitschende Blutliane';
UPDATE npcs SET gold = '26' WHERE name = 'Pfeilschnecke';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenassel';
UPDATE npcs SET gold = '0' WHERE name = 'Phasenenergiefalle (NPC)';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenfalter';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenfuchs';
UPDATE npcs SET gold = '1' WHERE name = 'Phasengeier';
UPDATE npcs SET gold = '1' WHERE name = 'Phasengreifer';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenhummer';
UPDATE npcs SET gold = '0' WHERE name = 'Phasenkiste';
UPDATE npcs SET gold = '2' WHERE name = 'Phasenkraken';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenkrebs';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenkrokodil';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenkuh';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenlibelle';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenlurch';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenmade';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenmücke';
UPDATE npcs SET gold = '0' WHERE name = 'Phasenportal';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenqualle';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenratte';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenraupe';
UPDATE npcs SET gold = '1' WHERE name = 'Phasensalamander';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenschabe';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenschaf';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenschildkröte';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenschlamm';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenschlange';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenschleim';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenschnecke';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenseestern';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenskelkos';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenskorpion';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenspinne';
UPDATE npcs SET gold = '1' WHERE name = 'Phasentiger';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenverbrenner';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenvogel';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenwiesel';
UPDATE npcs SET gold = '1' WHERE name = 'Phasenwolf';
UPDATE npcs SET gold = '2' WHERE name = 'Phasenwurm';
UPDATE npcs SET gold = '6' WHERE name = 'Pilzwachtel';
UPDATE npcs SET gold = '25' WHERE name = 'Pironer';
UPDATE npcs SET gold = '36' WHERE name = 'Plätscherfluss-Krokodil';
UPDATE npcs SET gold = '0' WHERE name = 'Portal des Feuers';
UPDATE npcs SET gold = '0' WHERE name = 'Portal des Wassers';
UPDATE npcs SET gold = '0' WHERE name = 'Portal in die Unterwelt';
UPDATE npcs SET gold = '0' WHERE name = 'Portalstab (NPC)';
UPDATE npcs SET gold = '3' WHERE name = 'Portalstab-Anbeter';
UPDATE npcs SET gold = '5' WHERE name = 'Randalierer';
UPDATE npcs SET gold = '55' WHERE name = 'Reen';
UPDATE npcs SET gold = '50' WHERE name = 'Reicher Wüstensalamander';
UPDATE npcs SET gold = '8' WHERE name = 'Reisender Fallensteller';
UPDATE npcs SET gold = '0' WHERE name = 'Resistenter Graustein-Bär';
UPDATE npcs SET gold = '0' WHERE name = 'Resistenter Schatten';
UPDATE npcs SET gold = '0' WHERE name = 'Resistenter Stachelschuss-Igel';
UPDATE npcs SET gold = '8' WHERE name = 'Riesenfalter-Kokon';
UPDATE npcs SET gold = '30' WHERE name = 'Riesenhornisse';
UPDATE npcs SET gold = '12' WHERE name = 'Riesenlibelle';
UPDATE npcs SET gold = '17' WHERE name = 'Riesige Gift-Dschungelschlange';
UPDATE npcs SET gold = '80' WHERE name = 'Riesige Landmuschel';
UPDATE npcs SET gold = '80' WHERE name = 'Riesige Schattenfledermaus';
UPDATE npcs SET gold = '1' WHERE name = 'Rindenhagel';
UPDATE npcs SET gold = '1' WHERE name = 'Rindenwalze';
UPDATE npcs SET gold = '4' WHERE name = 'Ringraupe';
UPDATE npcs SET gold = '20' WHERE name = 'Robuster Morschgreifer';
UPDATE npcs SET gold = '1' WHERE name = 'Robuster Spindelschreiter';
UPDATE npcs SET gold = '5' WHERE name = 'Rote Landkoralle';
UPDATE npcs SET gold = '20' WHERE name = 'Rote Riesenlibelle';
UPDATE npcs SET gold = '29' WHERE name = 'Rote Steinspinne';
UPDATE npcs SET gold = '2' WHERE name = 'Roteiskoralle';
UPDATE npcs SET gold = '17' WHERE name = 'Roter Baumkuschler';
UPDATE npcs SET gold = '12' WHERE name = 'Roter Felswurm';
UPDATE npcs SET gold = '46' WHERE name = 'Roter Sandhund';
UPDATE npcs SET gold = '15' WHERE name = 'Rotfell-Reh';
UPDATE npcs SET gold = '8' WHERE name = 'Rotfell-Rehkitz';
UPDATE npcs SET gold = '26' WHERE name = 'Rotpunkt-Tiger';
UPDATE npcs SET gold = '15' WHERE name = 'Rotschimmer-Ameise';
UPDATE npcs SET gold = '28' WHERE name = 'Rotzahnhai';
UPDATE npcs SET gold = '70' WHERE name = 'Rubinroter Waldgeist';
UPDATE npcs SET gold = '2' WHERE name = 'Ruinen-Wurm';
UPDATE npcs SET gold = '12' WHERE name = 'Ruinenschleicher';
UPDATE npcs SET gold = '35' WHERE name = 'Röhrenkrebs';
UPDATE npcs SET gold = '10' WHERE name = 'Saftende Itolos-Schrecke';
UPDATE npcs SET gold = '8' WHERE name = 'Salzsüchtiger Staubschleifer';
UPDATE npcs SET gold = '28' WHERE name = 'Salzwasservogel';
UPDATE npcs SET gold = '30' WHERE name = 'Sandalin';
UPDATE npcs SET gold = '29' WHERE name = 'Sandechse';
UPDATE npcs SET gold = '28' WHERE name = 'Sandfresserwurm';
UPDATE npcs SET gold = '17' WHERE name = 'Sandgeist';
UPDATE npcs SET gold = '15' WHERE name = 'Sandgolem';
UPDATE npcs SET gold = '20' WHERE name = 'Sandvogel';
UPDATE npcs SET gold = '15' WHERE name = 'Savannen-Vogel';
UPDATE npcs SET gold = '35' WHERE name = 'Schachtelmesserfarn';
UPDATE npcs SET gold = '24' WHERE name = 'Schaf';
UPDATE npcs SET gold = '8' WHERE name = 'Schatten der Dunkelheit';
UPDATE npcs SET gold = '15' WHERE name = 'Schatten des Weltenwandlers';
UPDATE npcs SET gold = '65' WHERE name = 'Schatten-Ei';
UPDATE npcs SET gold = '2' WHERE name = 'Schattenkreatur Gortari';
UPDATE npcs SET gold = '2' WHERE name = 'Schattenkreatur Jalakori';
UPDATE npcs SET gold = '2' WHERE name = 'Schattenkreatur Mantori';
UPDATE npcs SET gold = '2' WHERE name = 'Schattenkreatur Turwakori';
UPDATE npcs SET gold = '1' WHERE name = 'Schattenkreatur XY (Gruppen-NPC)';
UPDATE npcs SET gold = '1' WHERE name = 'Schattenkreatur XY (NPC)';
UPDATE npcs SET gold = '1' WHERE name = 'Schattenkreatur XY (Unique-NPC)';
UPDATE npcs SET gold = '100' WHERE name = 'Schattenkrokodil';
UPDATE npcs SET gold = '15' WHERE name = 'Schattenmoos';
UPDATE npcs SET gold = '18' WHERE name = 'Schattensalamander';
UPDATE npcs SET gold = '23' WHERE name = 'Schattenwesen';
UPDATE npcs SET gold = '2' WHERE name = 'Schattenwiesel';
UPDATE npcs SET gold = '12' WHERE name = 'Schattenwolf';
UPDATE npcs SET gold = '80' WHERE name = 'Schatzsucher (Unique-NPC)';
UPDATE npcs SET gold = '1' WHERE name = 'Schaufelmaulwurf';
UPDATE npcs SET gold = '18' WHERE name = 'Schlammkaktus';
UPDATE npcs SET gold = '9' WHERE name = 'Schleimraupe';
UPDATE npcs SET gold = '0' WHERE name = 'Schleuderfalle (NPC)';
UPDATE npcs SET gold = '16' WHERE name = 'Schlingende Lianenpeitsche';
UPDATE npcs SET gold = '9' WHERE name = 'Schlurum';
UPDATE npcs SET gold = '9' WHERE name = 'Schmatzende Blattspinne';
UPDATE npcs SET gold = '0' WHERE name = 'Schmerzfalle (NPC)';
UPDATE npcs SET gold = '30' WHERE name = 'Schmieriger Geschäftemacher';
UPDATE npcs SET gold = '6' WHERE name = 'Schneefisch';
UPDATE npcs SET gold = '12' WHERE name = 'Schneehase';
UPDATE npcs SET gold = '2' WHERE name = 'Schneehuhn';
UPDATE npcs SET gold = '12' WHERE name = 'Schneekäfer';
UPDATE npcs SET gold = '5' WHERE name = 'Schneekäfer-Kokon';
UPDATE npcs SET gold = '12' WHERE name = 'Schneekäfer-Raupe';
UPDATE npcs SET gold = '53' WHERE name = 'Schneesturmgeist';
UPDATE npcs SET gold = '2' WHERE name = 'Schneewiesel';
UPDATE npcs SET gold = '10' WHERE name = 'Schneeworan';
UPDATE npcs SET gold = '12' WHERE name = 'Schneewurm';
UPDATE npcs SET gold = '30' WHERE name = 'Schnelle Bernstein-Raupe';
UPDATE npcs SET gold = '15' WHERE name = 'Schneller Steinmolch';
UPDATE npcs SET gold = '19' WHERE name = 'Schneller Stororaptor';
UPDATE npcs SET gold = '14' WHERE name = 'Schnelles Tonar-Reptil';
UPDATE npcs SET gold = '0' WHERE name = 'Schnellflatter-Schmetterling';
UPDATE npcs SET gold = '18' WHERE name = 'Schotterraupe';
UPDATE npcs SET gold = '0' WHERE name = 'Schotterwurm';
UPDATE npcs SET gold = '5' WHERE name = 'Schwacher Sporenträger';
UPDATE npcs SET gold = '6' WHERE name = 'Schwacher Unterwelt-Dämon';
UPDATE npcs SET gold = '15' WHERE name = 'Schwaches Stachelkrokodil';
UPDATE npcs SET gold = '2' WHERE name = 'Schwangeres Schneehuhn';
UPDATE npcs SET gold = '23' WHERE name = 'Schwarze Keitel-Spinne';
UPDATE npcs SET gold = '34' WHERE name = 'Schwarzwespen';
UPDATE npcs SET gold = '120' WHERE name = 'Schwebende Goldkutsche';
UPDATE npcs SET gold = '6' WHERE name = 'Schwimmendes Tentakel';
UPDATE npcs SET gold = '0' WHERE name = 'Schwächefalle (NPC)';
UPDATE npcs SET gold = '2' WHERE name = 'Seeschlamm';
UPDATE npcs SET gold = '8' WHERE name = 'Seichtwasserpilz';
UPDATE npcs SET gold = '2' WHERE name = 'Seltsames Tier';
UPDATE npcs SET gold = '32' WHERE name = 'Serbanthi';
UPDATE npcs SET gold = '4' WHERE name = 'Seuchenflügler';
UPDATE npcs SET gold = '80' WHERE name = 'Siedestein-Dampfgeist';
UPDATE npcs SET gold = '30' WHERE name = 'Siedestein-Morschgreifer';
UPDATE npcs SET gold = '80' WHERE name = 'Siedesteinkäfer';
UPDATE npcs SET gold = '100' WHERE name = 'Silberfluss-Bär';
UPDATE npcs SET gold = '12' WHERE name = 'Silberfuchs';
UPDATE npcs SET gold = '21' WHERE name = 'Silbergras-Spinne';
UPDATE npcs SET gold = '2' WHERE name = 'Silberstein-Salamander';
UPDATE npcs SET gold = '23' WHERE name = 'Silberwurmhaufen';
UPDATE npcs SET gold = '100' WHERE name = 'Siramücken-Schwarm';
UPDATE npcs SET gold = '100' WHERE name = 'Sohn des Wiesengeistes';
UPDATE npcs SET gold = '21' WHERE name = 'Solarda-Fisch';
UPDATE npcs SET gold = '25' WHERE name = 'Spezialist für Erze';
UPDATE npcs SET gold = '1' WHERE name = 'Spindelschreiter';
UPDATE npcs SET gold = '50' WHERE name = 'Spindelschreiter-Überwacher';
UPDATE npcs SET gold = '100' WHERE name = 'Spinne der Staubnetze';
UPDATE npcs SET gold = '12' WHERE name = 'Sporenträger';
UPDATE npcs SET gold = '29' WHERE name = 'Sprungechse';
UPDATE npcs SET gold = '1' WHERE name = 'Spröder Ast';
UPDATE npcs SET gold = '1' WHERE name = 'Sprühregenwurm';
UPDATE npcs SET gold = '6' WHERE name = 'Stabfisch';
UPDATE npcs SET gold = '6' WHERE name = 'Stabkrebs';
UPDATE npcs SET gold = '18' WHERE name = 'Stabschrecke';
UPDATE npcs SET gold = '1' WHERE name = 'Stachelblutdickicht';
UPDATE npcs SET gold = '1' WHERE name = 'Stachelfisch';
UPDATE npcs SET gold = '23' WHERE name = 'Stachelkrokodil';
UPDATE npcs SET gold = '23' WHERE name = 'Stachelkäfer';
UPDATE npcs SET gold = '10' WHERE name = 'Stachelschildkröte';
UPDATE npcs SET gold = '34' WHERE name = 'Stachelschreck';
UPDATE npcs SET gold = '0' WHERE name = 'Starrfalle (NPC)';
UPDATE npcs SET gold = '23' WHERE name = 'Staub-Maus';
UPDATE npcs SET gold = '21' WHERE name = 'Staub-Skelett';
UPDATE npcs SET gold = '23' WHERE name = 'Staubassel';
UPDATE npcs SET gold = '18' WHERE name = 'Staubflatterer';
UPDATE npcs SET gold = '25' WHERE name = 'Staubgeist';
UPDATE npcs SET gold = '6' WHERE name = 'Staubige Pilzwachtel';
UPDATE npcs SET gold = '2' WHERE name = 'Staubkrieger';
UPDATE npcs SET gold = '8' WHERE name = 'Staubschleifer';
UPDATE npcs SET gold = '100' WHERE name = 'Staubschleifer-Königin';
UPDATE npcs SET gold = '13' WHERE name = 'Stechmücken';
UPDATE npcs SET gold = '2' WHERE name = 'Stegovar';
UPDATE npcs SET gold = '2' WHERE name = 'Stein-Koloss';
UPDATE npcs SET gold = '25' WHERE name = 'Stein-Skelkos';
UPDATE npcs SET gold = '17' WHERE name = 'Stein-Tentakel';
UPDATE npcs SET gold = '103' WHERE name = 'Steingolem';
UPDATE npcs SET gold = '8' WHERE name = 'Steinhuhn';
UPDATE npcs SET gold = '12' WHERE name = 'Steinkatze';
UPDATE npcs SET gold = '7' WHERE name = 'Steinkratzkäfer';
UPDATE npcs SET gold = '21' WHERE name = 'Steinkäfer';
UPDATE npcs SET gold = '15' WHERE name = 'Steinmolch';
UPDATE npcs SET gold = '12' WHERE name = 'Steinpicker-Vogel';
UPDATE npcs SET gold = '28' WHERE name = 'Steinschalenkäfer';
UPDATE npcs SET gold = '29' WHERE name = 'Steinspinne';
UPDATE npcs SET gold = '23' WHERE name = 'Steppenwolf';
UPDATE npcs SET gold = '12' WHERE name = 'Stepto-Waran';
UPDATE npcs SET gold = '18' WHERE name = 'Sterbliche Waldratte';
UPDATE npcs SET gold = '12' WHERE name = 'Sternenzerstörer';
UPDATE npcs SET gold = '0' WHERE name = 'Stolperfalle (NPC)';
UPDATE npcs SET gold = '18' WHERE name = 'Stororaptor';
UPDATE npcs SET gold = '33' WHERE name = 'Strandlokil';
UPDATE npcs SET gold = '12' WHERE name = 'Strauchkäfer';
UPDATE npcs SET gold = '2' WHERE name = 'Störrischer Stororaptor';
UPDATE npcs SET gold = '150' WHERE name = 'Sula-Echse';
UPDATE npcs SET gold = '12' WHERE name = 'Sumpflandkröte';
UPDATE npcs SET gold = '40' WHERE name = 'Sumpfschrecke';
UPDATE npcs SET gold = '20' WHERE name = 'Sumpfspinne';
UPDATE npcs SET gold = '12' WHERE name = 'Teidam';
UPDATE npcs SET gold = '14' WHERE name = 'Tempelhüpfer';
UPDATE npcs SET gold = '2' WHERE name = 'Tempelhüter';
UPDATE npcs SET gold = '0' WHERE name = 'Tempelschatz';
UPDATE npcs SET gold = '2' WHERE name = 'Tempelwächter';
UPDATE npcs SET gold = '12' WHERE name = 'Temporaler Falter';
UPDATE npcs SET gold = '57' WHERE name = 'Tentakel';
UPDATE npcs SET gold = '92' WHERE name = 'Tentakel aus Gold';
UPDATE npcs SET gold = '5' WHERE name = 'Thorom Logrid';
UPDATE npcs SET gold = '38' WHERE name = 'Tiefsee-Aal';
UPDATE npcs SET gold = '2' WHERE name = 'Tilua-Pflanze';
UPDATE npcs SET gold = '2' WHERE name = 'Todesflossen-Fisch';
UPDATE npcs SET gold = '58' WHERE name = 'Todesmoor-Krokodil';
UPDATE npcs SET gold = '3' WHERE name = 'Tolloschein-Fresser';
UPDATE npcs SET gold = '16' WHERE name = 'Tollwütiger Graustein-Bär';
UPDATE npcs SET gold = '26' WHERE name = 'Tonar-Reptil';
UPDATE npcs SET gold = '43' WHERE name = 'Tote Bergspitze';
UPDATE npcs SET gold = '6' WHERE name = 'Tote Kuh';
UPDATE npcs SET gold = '14' WHERE name = 'Totes Wawruz';
UPDATE npcs SET gold = '35' WHERE name = 'Transparenter Schatten';
UPDATE npcs SET gold = '28' WHERE name = 'Triefender Wandschleim';
UPDATE npcs SET gold = '38' WHERE name = 'Trockenwurm';
UPDATE npcs SET gold = '26' WHERE name = 'Tropfsteinwandler';
UPDATE npcs SET gold = '28' WHERE name = 'Tropfsteinwurm';
UPDATE npcs SET gold = '0' WHERE name = 'Turmgeist';
UPDATE npcs SET gold = '4' WHERE name = 'Tänzerin von Beispieluser';
UPDATE npcs SET gold = '1' WHERE name = 'Umnebeltes Schlangentier';
UPDATE npcs SET gold = '15' WHERE name = 'Unbekannter Affe';
UPDATE npcs SET gold = '28' WHERE name = 'Undaron';
UPDATE npcs SET gold = '22' WHERE name = 'Unsterbliche Waldratte';
UPDATE npcs SET gold = '8' WHERE name = 'Unterwelt-Dämon';
UPDATE npcs SET gold = '34' WHERE name = 'Untoter Bürger';
UPDATE npcs SET gold = '10' WHERE name = 'Untoter Bürgermeister';
UPDATE npcs SET gold = '34' WHERE name = 'Untoter Winterbürger';
UPDATE npcs SET gold = '0' WHERE name = 'Unverwüstliches Undaron';
UPDATE npcs SET gold = '1' WHERE name = 'Uralte Bluteiche';
UPDATE npcs SET gold = '10' WHERE name = 'Uralter Unterwelt-Dämon';
UPDATE npcs SET gold = '6' WHERE name = 'Urwaldkuh';
UPDATE npcs SET gold = '26' WHERE name = 'Urwaldschnecke';
UPDATE npcs SET gold = '200' WHERE name = 'Vater aller Stachelschuss-Igel';
UPDATE npcs SET gold = '4' WHERE name = 'Verirrter Aasgeier';
UPDATE npcs SET gold = '20' WHERE name = 'Verrosteter Wächtergolem';
UPDATE npcs SET gold = '21' WHERE name = 'Verrückter Frostdämon';
UPDATE npcs SET gold = '2' WHERE name = 'Verschneites Geröllwiesel';
UPDATE npcs SET gold = '16' WHERE name = 'Verstümmelter Morschgreifer';
UPDATE npcs SET gold = '14' WHERE name = 'Verstümmeltes Holzmonster';
UPDATE npcs SET gold = '80' WHERE name = 'Vertin';
UPDATE npcs SET gold = '8' WHERE name = 'Vertrockneter Seichtwasserpilz';
UPDATE npcs SET gold = '17' WHERE name = 'Verwehter Sandgeist';
UPDATE npcs SET gold = '12' WHERE name = 'Verwirrtes Schaf';
UPDATE npcs SET gold = '35' WHERE name = 'Verwirrtes Sägezahnblatt';
UPDATE npcs SET gold = '22' WHERE name = 'Verwundete Nebelmaus';
UPDATE npcs SET gold = '30' WHERE name = 'Verzauberte Nachtfledermaus';
UPDATE npcs SET gold = '17' WHERE name = 'Verzauberter Energiewurm';
UPDATE npcs SET gold = '8' WHERE name = 'Vorhof-Koordinator';
UPDATE npcs SET gold = '31' WHERE name = 'Vulkandämon';
UPDATE npcs SET gold = '20' WHERE name = 'Wachsamer Frostwolf';
UPDATE npcs SET gold = '25' WHERE name = 'Wahnsinniger Waldschlurch';
UPDATE npcs SET gold = '12' WHERE name = 'Waldhüpfer';
UPDATE npcs SET gold = '120' WHERE name = 'Waldmonster';
UPDATE npcs SET gold = '22' WHERE name = 'Waldratte';
UPDATE npcs SET gold = '23' WHERE name = 'Waldschlurch';
UPDATE npcs SET gold = '20' WHERE name = 'Waldschlurch-Skelett';
UPDATE npcs SET gold = '29' WHERE name = 'Waldspinne';
UPDATE npcs SET gold = '9' WHERE name = 'Waldvogel';
UPDATE npcs SET gold = '1' WHERE name = 'Wandelnde Blutesche';
UPDATE npcs SET gold = '100' WHERE name = 'Wandelnder Laubbaum';
UPDATE npcs SET gold = '28' WHERE name = 'Wandschleim';
UPDATE npcs SET gold = '2' WHERE name = 'Wasser-Schemen';
UPDATE npcs SET gold = '34' WHERE name = 'Wasserbär';
UPDATE npcs SET gold = '12' WHERE name = 'Wasserkatze';
UPDATE npcs SET gold = '36' WHERE name = 'Wasserschlange';
UPDATE npcs SET gold = '18' WHERE name = 'Wassertentakel';
UPDATE npcs SET gold = '14' WHERE name = 'Wawruz';
UPDATE npcs SET gold = '25' WHERE name = 'Wegelagerer';
UPDATE npcs SET gold = '1' WHERE name = 'Weinende Kastanie';
UPDATE npcs SET gold = '80' WHERE name = 'Weltenwandler';
UPDATE npcs SET gold = '21' WHERE name = 'Weltraum-Kraken';
UPDATE npcs SET gold = '16' WHERE name = 'Wendige Glypra';
UPDATE npcs SET gold = '2' WHERE name = 'Wetterkontroll-Magier';
UPDATE npcs SET gold = '2' WHERE name = 'Wiesenpfeifer';
UPDATE npcs SET gold = '26' WHERE name = 'Wiesenschrecke';
UPDATE npcs SET gold = '29' WHERE name = 'Windgeist';
UPDATE npcs SET gold = '29' WHERE name = 'Windgeist (Quest)';
UPDATE npcs SET gold = '1' WHERE name = 'Wirbelnder Rindenspeer';
UPDATE npcs SET gold = '12' WHERE name = 'Wolf der Finsternis';
UPDATE npcs SET gold = '2' WHERE name = 'Wolkenblume (NPC)';
UPDATE npcs SET gold = '8' WHERE name = 'Wolkenflatterer';
UPDATE npcs SET gold = '0' WHERE name = 'Wolkenkiste';
UPDATE npcs SET gold = '5' WHERE name = 'Wolkenschaf';
UPDATE npcs SET gold = '12' WHERE name = 'Wolliges Goldschaf';
UPDATE npcs SET gold = '2' WHERE name = 'Wucherwurzelbaum (NPC)';
UPDATE npcs SET gold = '1' WHERE name = 'Wurzelkralle';
UPDATE npcs SET gold = '1' WHERE name = 'Wurzelnde Blutpeitsche';
UPDATE npcs SET gold = '16' WHERE name = 'Wurzelwurm';
UPDATE npcs SET gold = '103' WHERE name = 'Wächter der Zelle';
UPDATE npcs SET gold = '46' WHERE name = 'Wächter des Vulkans';
UPDATE npcs SET gold = '20' WHERE name = 'Wächtergolem';
UPDATE npcs SET gold = '15' WHERE name = 'Wühlratte';
UPDATE npcs SET gold = '22' WHERE name = 'Wüsten-Ektofron';
UPDATE npcs SET gold = '100' WHERE name = 'Wüstenkrake';
UPDATE npcs SET gold = '2' WHERE name = 'Wüstenmaus';
UPDATE npcs SET gold = '23' WHERE name = 'Wüstenplankton';
UPDATE npcs SET gold = '2' WHERE name = 'Wüstensalamander';
UPDATE npcs SET gold = '40' WHERE name = 'Wüstenschreck';
UPDATE npcs SET gold = '23' WHERE name = 'Wüstenspinne';
UPDATE npcs SET gold = '10' WHERE name = 'Wütende Mooswurzel';
UPDATE npcs SET gold = '69' WHERE name = 'Zauberer der Bergwiesen';
UPDATE npcs SET gold = '1' WHERE name = 'Zielscheibe (NPC)';
UPDATE npcs SET gold = '8' WHERE name = 'Zitternde Mooswurzel';
UPDATE npcs SET gold = '0' WHERE name = 'Zottelfell-Hirsch';
UPDATE npcs SET gold = '9' WHERE name = 'Zukuvogel';
UPDATE npcs SET gold = '10' WHERE name = 'Zweibeinige Waldspinne';
UPDATE npcs SET gold = '1' WHERE name = 'Zäher Spindelschreiter';
